### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by micwoj92** [arlyon/instantly#2]
Rust 1.64.0
Installing with `cargo build --release` with 0594f06dae383bf14de60094d161a60d9e869509

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /home/micwoj92/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.12/src/sockaddr.rs:176:9
    |
176 |         mem::transmute::<SocketAddrV4, sockaddr_in>(v4);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `SocketAddrV4` (48 bits)
    = note: target type: `sockaddr_in` (128 bits)

For more information about this error, try `rustc --explain E0512`.
```

**Comment by arlyon** [comment]
Seems that older versions of socket2 no longer build with newer rust versions. I would take it up with them if you need to use that specific version, however I have updated the lockfile and fixed the associated build issues so please have another try.

Cheers

Alex

**Comment by micwoj92** [comment]
Thanks for the fix.
